# Generated by Django 3.0 on 2021-06-27 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constituency',
            name='geom',
        ),
        migrations.RemoveField(
            model_name='district',
            name='geom',
        ),
        migrations.RemoveField(
            model_name='province',
            name='geom',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='geom',
        ),
    ]
